version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
