name: OpenBSD
on:
  pull_request:
  push:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: test

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable

      - name: Build
        run: GOOS=openbsd GOARCH=amd64 go build

      - name: Test
        env:
          TEST_HOST: ${{ secrets.TEST_HOST }}
          TEST_KEY: ${{ secrets.TEST_KEY }}
          TEST_PUB: ${{ secrets.TEST_PUB }}
        run: |
          mkdir -p ~/.ssh
          echo "${TEST_KEY}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${TEST_PUB}" > ~/.ssh/known_hosts

          set -ex
          remote="ip.wtf-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
          scp ip.wtf "${TEST_HOST}:${remote}"
          ssh "${TEST_HOST}" "trap 'rm -f ${remote}' EXIT
            set -mbxeuo pipefail
            ./$remote -help
            ./$remote &
            sleep 2
            curl --json '' -s localhost:8080 | jq -r .ip
            curl -s --user-agent Mozilla/5.0 localhost:8080 | xmllint --html - | grep -A1 'IPv4<'
            kill %1
            fg || :; [[ $? = 143 ]]" | tee out
          [[ $(grep -c 127.0.0.1 out) = 2 ]]
